// ===========================================================================
// 00_base_measures_EN.dax
// BASE measures shared by every page. Integrate these FIRST, in table _Mesures.
// ---------------------------------------------------------------------------
// Model: constellation, 3 facts (FACT_LOAN, FACT_RESERVATION,
//        FACT_INVENTORY_SNAPSHOT) + 5 dimensions.
// DIM_DATE must be marked as a date table on [full_date].
//
// TYPE CONVENTIONS (verify at import):
//   - is_exam_period, is_weekend, out_of_stock  -> Boolean  => compare to TRUE()
//     If Power BI imported them as TEXT, replace "= TRUE()" with '= "True"'.
//   - all *_id, durations, counters                -> Whole number
//   - utilization_rate, availability_rate, penalty_amount -> Decimal
//
// SNAPSHOT RULE: FACT_INVENTORY_SNAPSHOT is a monthly periodic snapshot.
//   NEVER sum its columns across time. Aggregate within a single month
//   (SUM is fine), and for a "current state" KPI pin the latest snapshot
//   (see [_Last Snapshot Date]).
// ===========================================================================


// --- LOANS ----------------------------------------------------------------

Total Loans = COUNTROWS ( FACT_LOAN )

Open Loans =
CALCULATE ( COUNTROWS ( FACT_LOAN ), ISBLANK ( FACT_LOAN[return_date] ) )

Closed Loans =
CALCULATE ( COUNTROWS ( FACT_LOAN ), NOT ISBLANK ( FACT_LOAN[return_date] ) )

Loaned Quantity = SUM ( FACT_LOAN[quantity] )


// --- RESERVATIONS ---------------------------------------------------------

Total Reservations = COUNTROWS ( FACT_RESERVATION )

Fulfilled Reservations =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "fulfilled" )

Pending Reservations =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "pending" )

Cancelled Reservations =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "cancelled" )


// --- USEFUL CARDINALITIES -------------------------------------------------

Active Users = DISTINCTCOUNT ( FACT_LOAN[user_id] )

Distinct Books Loaned = DISTINCTCOUNT ( FACT_LOAN[book_id] )

Active Branches = DISTINCTCOUNT ( FACT_LOAN[branch_id] )

Active Days = DISTINCTCOUNT ( FACT_LOAN[date_id] )   // days with at least 1 loan


// --- SNAPSHOT HELPER ------------------------------------------------------
// Returns the date_id of the latest snapshot in the current context (respects
// slicers via ALLSELECTED). Used to pin "current state" stock KPIs.

_Last Snapshot Date =
CALCULATE (
    MAX ( FACT_INVENTORY_SNAPSHOT[date_id] ),
    ALLSELECTED ( DIM_DATE )
)
