// ===========================================================================
// 01_raphael_pages_1_2_EN.dax
// Page 1: Loans overview (volume, trend, growth)
// Page 2: Time analysis & exam periods
// ---------------------------------------------------------------------------
// Depends on 00_base_measures_EN.dax (e.g. [Total Loans]).
// DIM_DATE marked as a date table on [full_date].
//
// NOTE (audit): Raphael already named his measures in English INSIDE his .pbix,
// but with an inconsistent convention (e.g. "AVD daily loans", "Cumul Loans
// (running)", "NB Exam Days", "Loans Week-end %"). The names below are the
// harmonised English convention for the merged master file. If you keep his
// original names instead, just keep the mapping in TRANSLATION_MAP.md handy so
// the report visuals still resolve.
// ===========================================================================


// =========================== PAGE 1 — OVERVIEW ============================

Avg Daily Loans =
DIVIDE ( [Total Loans], COUNTROWS ( DIM_DATE ) )
// average over the calendar in context (working days + weekends)

Loans YTD =
TOTALYTD ( [Total Loans], DIM_DATE[full_date] )

Loans LY =
CALCULATE ( [Total Loans], SAMEPERIODLASTYEAR ( DIM_DATE[full_date] ) )

Loans YoY % =
VAR Prev = [Loans LY]
RETURN DIVIDE ( [Total Loans] - Prev, Prev )

Loans LM =
CALCULATE ( [Total Loans], DATEADD ( DIM_DATE[full_date], -1, MONTH ) )

Loans MoM % =
VAR Prev = [Loans LM]
RETURN DIVIDE ( [Total Loans] - Prev, Prev )

Running Total Loans =
CALCULATE (
    [Total Loans],
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[full_date] <= MAX ( DIM_DATE[full_date] ) )
)


// =========================== PAGE 2 — TIME & EXAMS ========================

Loans (Exam Period) =
CALCULATE ( [Total Loans], DIM_DATE[is_exam_period] = TRUE () )

Loans (Off-Exam) =
CALCULATE ( [Total Loans], DIM_DATE[is_exam_period] = FALSE () )

Exam-Period Loans % =
DIVIDE ( [Loans (Exam Period)], [Total Loans] )

// number of exam / non-exam days in context
_Exam Days =
CALCULATE ( COUNTROWS ( DIM_DATE ), DIM_DATE[is_exam_period] = TRUE () )

_Off-Exam Days =
CALCULATE ( COUNTROWS ( DIM_DATE ), DIM_DATE[is_exam_period] = FALSE () )

Daily Loans (Exam Period) =
DIVIDE ( [Loans (Exam Period)], [_Exam Days] )

Daily Loans (Off-Exam) =
DIVIDE ( [Loans (Off-Exam)], [_Off-Exam Days] )

// KEY signal of page 2: exam-period over-intensity.
// Cross with DIM_CATEGORY to show the interaction effect
// (Law / Health / Data ~x2.8 ; Literature / Humanities ~x1.7).
Exam Overload Index =
DIVIDE ( [Daily Loans (Exam Period)], [Daily Loans (Off-Exam)] )

// loans by academic period (Back-to-School / Exams / Off-Exam / Summer Break)
// -> put DIM_DATE[academic_period] directly on the axis, no dedicated measure needed.

Weekend Loans % =
DIVIDE (
    CALCULATE ( [Total Loans], DIM_DATE[is_weekend] = TRUE () ),
    [Total Loans]
)
