// Mathieu — Pages 5 & 6
// Version une seule table de faits : FACT_LIBRARY.

DEFINE
    MEASURE 'FACT_LIBRARY'[Total Emprunts] =
        CALCULATE ( COUNTROWS ( 'FACT_LIBRARY' ), 'FACT_LIBRARY'[event_type] = "loan" )

    MEASURE 'FACT_LIBRARY'[Total Réservations] =
        CALCULATE ( COUNTROWS ( 'FACT_LIBRARY' ), 'FACT_LIBRARY'[event_type] = "reservation" )

    MEASURE 'FACT_LIBRARY'[Total Exemplaires] =
        CALCULATE ( SUM ( 'FACT_LIBRARY'[total_copies] ), 'FACT_LIBRARY'[event_type] = "inventory_snapshot", REMOVEFILTERS ( 'DIM_DATE' ) )

    MEASURE 'FACT_LIBRARY'[Exemplaires Disponibles] =
        CALCULATE ( SUM ( 'FACT_LIBRARY'[available_copies] ), 'FACT_LIBRARY'[event_type] = "inventory_snapshot", REMOVEFILTERS ( 'DIM_DATE' ) )

    MEASURE 'FACT_LIBRARY'[Exemplaires Occupés] =
        CALCULATE ( SUM ( 'FACT_LIBRARY'[active_loans] ), 'FACT_LIBRARY'[event_type] = "inventory_snapshot", REMOVEFILTERS ( 'DIM_DATE' ) )

    MEASURE 'FACT_LIBRARY'[Availability Rate] =
        DIVIDE ( [Exemplaires Disponibles], [Total Exemplaires] )

    MEASURE 'FACT_LIBRARY'[Utilization Rate] =
        DIVIDE ( [Exemplaires Occupés], [Total Exemplaires] )

    MEASURE 'FACT_LIBRARY'[Titres en Rupture] =
        COUNTROWS (
            FILTER (
                ADDCOLUMNS (
                    VALUES ( 'DIM_BOOK'[book_id] ),
                    "CopiesDisponibles",
                        CALCULATE (
                            SUM ( 'FACT_LIBRARY'[available_copies] ),
                            'FACT_LIBRARY'[event_type] = "inventory_snapshot",
                            REMOVEFILTERS ( 'DIM_DATE' )
                        )
                ),
                [CopiesDisponibles] = 0
            )
        )

    MEASURE 'FACT_LIBRARY'[Réservations Pending] =
        CALCULATE ( COUNTROWS ( 'FACT_LIBRARY' ), 'FACT_LIBRARY'[event_type] = "reservation", 'FACT_LIBRARY'[reservation_status] = "pending" )

    MEASURE 'FACT_LIBRARY'[Réservations Cancelled] =
        CALCULATE ( COUNTROWS ( 'FACT_LIBRARY' ), 'FACT_LIBRARY'[event_type] = "reservation", 'FACT_LIBRARY'[reservation_status] = "cancelled" )

    MEASURE 'FACT_LIBRARY'[Réservations Non Satisfaites] =
        [Réservations Pending] + [Réservations Cancelled]

    MEASURE 'FACT_LIBRARY'[Délai d’Attente Moyen] =
        CALCULATE ( AVERAGE ( 'FACT_LIBRARY'[wait_days] ), 'FACT_LIBRARY'[event_type] = "reservation" )

    MEASURE 'FACT_LIBRARY'[Score Tension Stock] =
        [Utilization Rate] * 0.7
            + DIVIDE ( [Réservations Non Satisfaites], [Total Exemplaires] ) * 0.3

EVALUATE
SUMMARIZECOLUMNS (
    'DIM_BOOK'[title],
    'DIM_BRANCH'[branch_name],
    "Exemplaires", [Total Exemplaires],
    "Disponibles", [Exemplaires Disponibles],
    "Occupation", [Utilization Rate],
    "Réservations non satisfaites", [Réservations Non Satisfaites]
)
