// ===========================================================================
// mathieu_pages_5_6.dax
// Page 5 : Catalogue & reservations (Pareto livres, demande, satisfaction)
// Page 6 : Stock & moteur de reallocation prescriptif  <-- differenciant
// ---------------------------------------------------------------------------
// Depend de mesures_validees_modele_commun.dax (dont [_Date Dernier Snapshot]).
//
// PAGE 6 — REGLE D'OR DU SNAPSHOT :
//   FACT_INVENTORY_SNAPSHOT est un snapshot mensuel. On NE SOMME PAS dans le
//   temps. Deux familles de mesures ci-dessous :
//     (a) "... (mois)"        -> SUM correct A CONDITION qu'un seul mois soit en
//                                contexte (mois en axe, ou slicer sur un mois).
//     (b) "... (dernier mois)"-> epingle le dernier snapshot via le helper, pour
//                                les cartes KPI "etat courant". Ne pas mettre de
//                                mois en axe avec ces mesures.
// ===========================================================================


// =========================== PAGE 5 — CATALOGUE & RESERVATIONS =============

// --- Pareto livres ---
Rang Livre =
IF (
    HASONEVALUE ( DIM_BOOK[book_id] ),
    RANKX ( ALL ( DIM_BOOK[book_id] ), [Total Emprunts],, DESC, DENSE )
)

% Emprunts Cumule (Pareto) =
VAR T = ADDCOLUMNS ( ALL ( DIM_BOOK[book_id] ), "@l", [Total Emprunts] )
VAR Cur = [Total Emprunts]
VAR CumLoans = SUMX ( FILTER ( T, [@l] >= Cur ), [@l] )
VAR Grand = SUMX ( T, [@l] )
RETURN DIVIDE ( CumLoans, Grand )

// carte : part des emprunts captee par les 20% de livres les plus demandes (~44%)
Part Emprunts Top 20% Livres % =
VAR N = COUNTROWS ( ALL ( DIM_BOOK[book_id] ) )
VAR TopN = ROUNDUP ( N * 0.2, 0 )
VAR T = ADDCOLUMNS ( ALL ( DIM_BOOK[book_id] ), "@l", [Total Emprunts] )
VAR TopBooks = TOPN ( TopN, T, [@l], DESC )
RETURN DIVIDE ( SUMX ( TopBooks, [@l] ), SUMX ( T, [@l] ) )

// --- reservations ---
Taux Satisfaction Reservations % =
DIVIDE ( [Reservations Satisfaites], [Total Reservations] )

Taux Annulation Reservations % =
DIVIDE ( [Reservations Annulees], [Total Reservations] )

Attente Moyenne Reservation (j) =
AVERAGE ( FACT_RESERVATION[wait_days] )

// indicateur de demande refoulee : plus c'est haut, plus le livre/branche coince
Pression Demande (Resa par Empr) =
DIVIDE ( [Total Reservations], [Total Emprunts] )


// =========================== PAGE 6 — STOCK & REALLOCATION =================

// --- etat de stock, dernier snapshot (cartes KPI) ---

Stock Exemplaires Totaux (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    SUM ( FACT_INVENTORY_SNAPSHOT[total_copies] ),
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

Stock Exemplaires Disponibles (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    SUM ( FACT_INVENTORY_SNAPSHOT[available_copies] ),
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

Taux d'Occupation Moyen (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    AVERAGE ( FACT_INVENTORY_SNAPSHOT[utilization_rate] ),
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

Taux de Rupture % (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    DIVIDE (
        CALCULATE (
            COUNTROWS ( FACT_INVENTORY_SNAPSHOT ),
            FACT_INVENTORY_SNAPSHOT[out_of_stock] = TRUE ()
        ),
        COUNTROWS ( FACT_INVENTORY_SNAPSHOT )
    ),
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

// --- versions "mois" pour les courbes temporelles (mettre le mois en axe) ---

Taux d'Occupation Moyen (mois) =
AVERAGE ( FACT_INVENTORY_SNAPSHOT[utilization_rate] )

Reservations Non Satisfaites (mois) =
SUM ( FACT_INVENTORY_SNAPSHOT[unsatisfied_reservations] )


// --- MOTEUR DE REALLOCATION (le coeur de la page) ---

// couples livre x branche en tension critique au dernier snapshot
Couples Critiques (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    COUNTROWS ( FACT_INVENTORY_SNAPSHOT ),
    FACT_INVENTORY_SNAPSHOT[reallocation_priority] = "Critique",
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

// demande non satisfaite au dernier snapshot (exemplaires manquants)
Demande Non Satisfaite (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    SUM ( FACT_INVENTORY_SNAPSHOT[unsatisfied_reservations] ),
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

// exemplaires dormants : disponibles dans des couples a priorite Faible
Exemplaires Dormants (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    SUM ( FACT_INVENTORY_SNAPSHOT[available_copies] ),
    FACT_INVENTORY_SNAPSHOT[reallocation_priority] = "Faible",
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

// exemplaires REELLEMENT mobilisables : on laisse 1 copie de securite par couple
Exemplaires Dormants Mobilisables (dernier mois) =
VAR d = [_Date Dernier Snapshot]
RETURN
CALCULATE (
    SUMX (
        FACT_INVENTORY_SNAPSHOT,
        MAX ( FACT_INVENTORY_SNAPSHOT[available_copies] - 1, 0 )
    ),
    FACT_INVENTORY_SNAPSHOT[reallocation_priority] = "Faible",
    FACT_INVENTORY_SNAPSHOT[available_copies] >= 2,
    FILTER ( ALL ( DIM_DATE ), DIM_DATE[date_id] = d )
)

// LE chiffre de soutenance : combien de la demande non satisfaite pourrait etre
// couverte rien qu'en redistribuant le stock dormant existant ?
Taux de Couverture Reallocation % =
DIVIDE (
    [Exemplaires Dormants Mobilisables (dernier mois)],
    [Demande Non Satisfaite (dernier mois)]
)

// Pour le visuel "tableau de reallocation" : mettre DIM_BOOK[title] et
// DIM_BRANCH[branch_name] en lignes, et la colonne FACT_INVENTORY_SNAPSHOT
// [reallocation_priority] + les mesures Disponibles / Non Satisfaites.
// Filtrer sur le dernier mois. Lecture directe : priorite Critique avec demande
// non satisfaite d'un cote, Faible avec disponibles de l'autre = ordre de transfert.
