// ===========================================================================
// samuel_pages_3_4.dax
// Page 3 : Analyse par branche (charge, classement, geographie, croissance)
// Page 4 : Usagers & comportement (segmentation, retards, penalites)
// ---------------------------------------------------------------------------
// Depend de mesures_validees_modele_commun.dax.
// ===========================================================================


// =========================== PAGE 3 — BRANCHES =============================

// part d'emprunts d'une branche dans le total (toutes branches)
Part Emprunts Branche % =
DIVIDE ( [Total Emprunts], CALCULATE ( [Total Emprunts], ALL ( DIM_BRANCH ) ) )

// classement des branches par volume
Rang Branche =
IF (
    HASONEVALUE ( DIM_BRANCH[branch_name] ),
    RANKX ( ALL ( DIM_BRANCH[branch_name] ), [Total Emprunts],, DESC, DENSE )
)

// emprunts moyens par jour d'une branche -> compare la charge reelle
Charge Moyenne Branche (empr/j) =
DIVIDE ( [Total Emprunts], COUNTROWS ( DIM_DATE ) )

// croissance YoY par branche : sert a faire ressortir Bruxelles (hub emergent)
Croissance Branche YoY % =
VAR Prec = CALCULATE ( [Total Emprunts], SAMEPERIODLASTYEAR ( DIM_DATE[full_date] ) )
RETURN DIVIDE ( [Total Emprunts] - Prec, Prec )

// reservations non satisfaites cote branche (pression de la demande)
Taux Annulation Reservations Branche % =
DIVIDE ( [Reservations Annulees], [Total Reservations] )

Attente Moyenne Branche (j) =
AVERAGE ( FACT_RESERVATION[wait_days] )


// =========================== PAGE 4 — USAGERS =============================

Emprunts par Usager =
DIVIDE ( [Total Emprunts], [Usagers Actifs] )

// --- retards ---
Emprunts En Retard =
CALCULATE ( COUNTROWS ( FACT_LOAN ), FACT_LOAN[days_overdue] > 0 )

Taux de Retard % =
DIVIDE ( [Emprunts En Retard], [Emprunts Clotures] )
// note : on rapporte aux emprunts CLOTURES (un emprunt en cours n'est pas "en retard" ici)

Retard Moyen (jours, retards seuls) =
AVERAGEX ( FILTER ( FACT_LOAN, FACT_LOAN[days_overdue] > 0 ), FACT_LOAN[days_overdue] )

Jours de Retard Cumules =
SUM ( FACT_LOAN[days_overdue] )

// --- penalites ---
Penalites Totales = SUM ( FACT_LOAN[penalty_amount] )

Penalite Moyenne par Usager =
DIVIDE ( [Penalites Totales], [Usagers Actifs] )

// --- duree de pret ---
Duree Moyenne de Pret (j) =
AVERAGE ( FACT_LOAN[loan_duration_days] )

// Les segments (Student / Researcher / Faculty) et facultes se mettent en axe
// via DIM_USER[user_type] / DIM_USER[faculty] : les mesures ci-dessus reagissent
// au contexte. Signal attendu : Student ~24.8% de retard vs Faculty ~14.5%.

// usagers ayant emprunte vs base totale d'usagers (taux d'activation)
Taux d'Activite Usagers % =
DIVIDE ( [Usagers Actifs], COUNTROWS ( ALL ( DIM_USER ) ) )
