// ===========================================================================
// mesures_validees_modele_commun.dax
// Mesures de BASE partagees par toutes les pages. A integrer en premier.
// ---------------------------------------------------------------------------
// Modele : constellation 3 facts (FACT_LOAN, FACT_RESERVATION,
//          FACT_INVENTORY_SNAPSHOT) + 5 dimensions.
// DIM_DATE doit etre marquee comme table de dates sur [full_date].
//
// CONVENTIONS DE TYPE (verifier a l'import) :
//   - is_exam_period, is_weekend, out_of_stock  -> Booleen  => comparer a TRUE()
//     Si Power BI les a importes en TEXTE, remplacer "= TRUE()" par '= "True"'.
//   - tous les *_id, durees, compteurs           -> Nombre entier
//   - utilization_rate, availability_rate, penalty_amount -> Decimal
//
// RAPPEL SNAPSHOT : FACT_INVENTORY_SNAPSHOT est un snapshot periodique mensuel.
//   Ne JAMAIS sommer ses colonnes a travers le temps. On agrege au sein d'un
//   mois (SUM correct), et pour un KPI "etat courant" on epingle le dernier
//   snapshot (voir [_Date Dernier Snapshot]).
// ===========================================================================


// --- EMPRUNTS -------------------------------------------------------------

Total Emprunts = COUNTROWS ( FACT_LOAN )

Emprunts En Cours =
CALCULATE ( COUNTROWS ( FACT_LOAN ), ISBLANK ( FACT_LOAN[return_date] ) )

Emprunts Clotures =
CALCULATE ( COUNTROWS ( FACT_LOAN ), NOT ISBLANK ( FACT_LOAN[return_date] ) )

Quantite Empruntee = SUM ( FACT_LOAN[quantity] )


// --- RESERVATIONS ---------------------------------------------------------

Total Reservations = COUNTROWS ( FACT_RESERVATION )

Reservations Satisfaites =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "fulfilled" )

Reservations En Attente =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "pending" )

Reservations Annulees =
CALCULATE ( [Total Reservations], FACT_RESERVATION[reservation_status] = "cancelled" )


// --- CARDINALITES UTILES --------------------------------------------------

Usagers Actifs = DISTINCTCOUNT ( FACT_LOAN[user_id] )

Livres Distincts Empruntes = DISTINCTCOUNT ( FACT_LOAN[book_id] )

Branches Actives = DISTINCTCOUNT ( FACT_LOAN[branch_id] )

Nb Jours = DISTINCTCOUNT ( FACT_LOAN[date_id] )   // jours avec au moins 1 emprunt


// --- HELPER SNAPSHOT ------------------------------------------------------
// Renvoie le date_id du dernier snapshot dans le contexte (respecte les
// slicers via ALLSELECTED). Sert a epingler les KPI de stock "etat courant".

_Date Dernier Snapshot =
CALCULATE (
    MAX ( FACT_INVENTORY_SNAPSHOT[date_id] ),
    ALLSELECTED ( DIM_DATE )
)
