// ===========================================================================
// 02_samuel_pages_3_4_EN.dax
// Page 3: Branch analysis (load, ranking, geography, growth)
// Page 4: Users & behaviour (segmentation, overdue, penalties)
// =========================== PAGE 3 — BRANCHES ============================

// share of a branch's loans in the total (all branches)
Branch Loans Share % =
DIVIDE ( [Total Loans], CALCULATE ( [Total Loans], ALL ( DIM_BRANCH ) ) )

// branch ranking by volume
Branch Rank =
IF (
    HASONEVALUE ( DIM_BRANCH[branch_name] ),
    RANKX ( ALL ( DIM_BRANCH[branch_name] ), [Total Loans],, DESC, DENSE )
)

// average loans per day for a branch -> compares actual load
Avg Branch Load (loans/day) =
DIVIDE ( [Total Loans], COUNTROWS ( DIM_DATE ) )

// branch YoY growth: highlights Brussels (emerging hub)
Branch Loans YoY % =
VAR Prev = CALCULATE ( [Total Loans], SAMEPERIODLASTYEAR ( DIM_DATE[full_date] ) )
RETURN DIVIDE ( [Total Loans] - Prev, Prev )

// unmet demand on the branch side (demand pressure)
Branch Reservation Cancel Rate % =
DIVIDE ( [Cancelled Reservations], [Total Reservations] )

Avg Branch Wait (days) =
AVERAGE ( FACT_RESERVATION[wait_days] )


// =========================== PAGE 4 — USERS ===============================

Loans per User =
DIVIDE ( [Total Loans], [Active Users] )

// --- overdue ---
Overdue Loans =
CALCULATE ( COUNTROWS ( FACT_LOAN ), FACT_LOAN[days_overdue] > 0 )

Overdue Rate % =
DIVIDE ( [Overdue Loans], [Closed Loans] )
// note: measured against CLOSED loans (an open loan is not "overdue" here)

Avg Overdue Days (overdue only) =
AVERAGEX ( FILTER ( FACT_LOAN, FACT_LOAN[days_overdue] > 0 ), FACT_LOAN[days_overdue] )

Total Overdue Days =
SUM ( FACT_LOAN[days_overdue] )

// --- penalties ---
Total Penalties = SUM ( FACT_LOAN[penalty_amount] )

Avg Penalty per User =
DIVIDE ( [Total Penalties], [Active Users] )

// --- loan duration ---
Avg Loan Duration (days) =
AVERAGE ( FACT_LOAN[loan_duration_days] )

// Segments (Student / Researcher / Faculty) and faculties go on the axis
// via DIM_USER[user_type] / DIM_USER[faculty]: the measures above react to
// context. Expected signal: Student ~24.8% overdue vs Faculty ~14.5%.

// users who borrowed vs total user base (activation rate)
User Activation Rate % =
DIVIDE ( [Active Users], COUNTROWS ( ALL ( DIM_USER ) ) )
